"""Pydantic data schemas for SceneExpert MVP.

All inter-module data contracts are defined here to ensure
type safety and easy JSON serialization across the pipeline.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# TaskCompiler output
# ---------------------------------------------------------------------------


class SceneTaskSpec(BaseModel):
    """Structured scene requirements extracted from a raw text prompt."""

    room_type: str = Field(
        ..., description="Primary room type, e.g. 'bedroom', 'kitchen'"
    )
    style: str = Field(
        ..., description="Aesthetic style, e.g. 'cozy modern', 'industrial'"
    )
    required_large_objects: list[str] = Field(
        default_factory=list,
        description="Furniture-scale objects that must be present (floor plan / furniture stage)",
    )
    required_wall_objects: list[str] = Field(
        default_factory=list,
        description="Wall-mounted objects required",
    )
    required_ceiling_objects: list[str] = Field(
        default_factory=list,
        description="Ceiling-mounted objects required",
    )
    required_small_objects: list[str] = Field(
        default_factory=list,
        description="Manipuland-scale objects required (books, cups, etc.)",
    )
    functional_zones: list[str] = Field(
        default_factory=list,
        description="Spatial zones within the room, e.g. ['sleeping_zone', 'working_zone']",
    )
    interaction_constraints: list[str] = Field(
        default_factory=list,
        description="Robot-interaction constraints: reachability, clearance, support surface rules",
    )
    aesthetic_constraints: list[str] = Field(
        default_factory=list,
        description="Visual / style constraints: material palette, density, symmetry, etc.",
    )


# ---------------------------------------------------------------------------
# Memory pack returned by retriever
# ---------------------------------------------------------------------------


class MemoryPack(BaseModel):
    """Retrieved memory snippets to inject into a stage's StageBrief."""

    success_hints: list[str] = Field(
        default_factory=list,
        description="Compressed text hints from successful similar cases (for GlobalPlanner)",
    )
    failure_hints: list[str] = Field(
        default_factory=list,
        description="Avoid-rule hints derived from failure cases",
    )
    skill_texts: list[str] = Field(
        default_factory=list,
        description="Skill procedure texts formatted for prompt injection",
    )
    placement_reference: str = Field(
        default="",
        description=(
            "Formatted placement reference block from the top success case. "
            "Injected directly into the designer prompt, bypassing GlobalPlanner."
        ),
    )


# ---------------------------------------------------------------------------
# Harness internals
# ---------------------------------------------------------------------------


class StageBudget(BaseModel):
    """Per-stage execution budget."""

    max_designer_iterations: int = 2
    max_repair_steps: int = 1


class HarnessContext(BaseModel):
    """All inputs the Harness assembles before executing a SceneSmith stage."""

    stage: str
    task_spec: SceneTaskSpec
    memory_pack: MemoryPack
    stage_brief: "StageBrief | None" = None
    stage_budget: StageBudget = Field(default_factory=StageBudget)
    allowed_scene_smith_stage: str = ""

    model_config = {"arbitrary_types_allowed": True}


# ---------------------------------------------------------------------------
# Global Planner output
# ---------------------------------------------------------------------------


class StageBrief(BaseModel):
    """Expert planning hint generated by the Global Planner for one stage."""

    stage: str
    stage_objective: str = Field(
        ...,
        description="One-sentence goal for this stage",
    )
    recommended_skills: list[str] = Field(
        default_factory=list,
        description="Names of skills from memory to apply",
    )
    constraints_for_designer: list[str] = Field(
        default_factory=list,
        description="Concrete placement/arrangement constraints for the designer agent",
    )
    checks_for_critic: list[str] = Field(
        default_factory=list,
        description="Verification items the critic should evaluate",
    )
    failure_patterns_to_avoid: list[str] = Field(
        default_factory=list,
        description="Known failure patterns retrieved from memory to explicitly avoid",
    )

    def to_injection_text(self) -> str:
        """Format StageBrief as a compact text block for prompt injection."""
        lines = [
            f"=== SceneExpert Stage Brief: {self.stage} ===",
            f"Objective: {self.stage_objective}",
        ]
        if self.constraints_for_designer:
            lines.append("Designer constraints:")
            lines.extend(f"  - {c}" for c in self.constraints_for_designer)
        if self.failure_patterns_to_avoid:
            lines.append("Known failure patterns to avoid:")
            lines.extend(f"  - {p}" for p in self.failure_patterns_to_avoid)
        if self.checks_for_critic:
            lines.append("Critic should verify:")
            lines.extend(f"  - {c}" for c in self.checks_for_critic)
        if self.recommended_skills:
            lines.append(f"Recommended skills: {', '.join(self.recommended_skills)}")
        lines.append("=== End Stage Brief ===")
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Verifier outputs
# ---------------------------------------------------------------------------


class VerifyIssue(BaseModel):
    issue_type: str  # e.g., "unreachable", "missing_object", "overcrowded"
    object_name: str = ""
    description: str = ""


class StageVerifyReport(BaseModel):
    """Verification result after a single SceneSmith stage."""

    stage: str
    pass_stage: bool
    scores: dict[str, float] = Field(
        default_factory=dict,
        description="Scores 0-1 for semantic, aesthetic, physics, interaction",
    )
    issues: list[VerifyIssue] = Field(default_factory=list)
    repair_suggestions: list[str] = Field(default_factory=list)
    critique_summary: str = Field(
        default="",
        description="Full critic summary text from SceneSmith scores.yaml — richest signal for memory",
    )


class FullVerifyReport(BaseModel):
    """Final whole-scene verification result."""

    semantic_score: float = 0.0
    aesthetic_score: float = 0.0
    plausibility_score: float = 0.0
    style_consistency: float = 0.0
    collision_free_rate: float = 0.0
    stability_score: float = 0.0
    walkable_area_ratio: float = 0.0
    reachability_score: float = 0.0
    support_relation_accuracy: float = 0.0
    overall_score: float = 0.0
    pass_scene: bool = False


# ---------------------------------------------------------------------------
# Repair Controller
# ---------------------------------------------------------------------------


class RepairResult(BaseModel):
    """Outcome of a repair attempt."""

    repair_type: str  # "local_repair", "stage_regeneration", "rollback", "skipped"
    failure_type: str = ""
    repair_action: str = ""
    repair_verified: bool = False
    new_scene_state: str = ""


# ---------------------------------------------------------------------------
# Trace entry (per stage)
# ---------------------------------------------------------------------------


class StageCost(BaseModel):
    qwen_calls: int = 0
    stage_time_sec: float = 0.0


class StageTraceEntry(BaseModel):
    stage: str
    memory_pack: MemoryPack
    stage_brief: StageBrief | None = None
    scene_state_path: str = ""
    verify_report: StageVerifyReport | None = None
    repair_actions: list[RepairResult] = Field(default_factory=list)
    cost: StageCost = Field(default_factory=StageCost)
